### ISSUE TITLE
how do I skip EAC?

### ISSUE THREAD

**Issue by cjuwen** [prebombo/helldivers-2-CT#1]
Hello, how do I skip EAC?

**Comment by cjuwen** [comment]
Please, can you tell me?

**Comment by prebombo** [comment]
If with EasyAntiCheat you mean GameGuardian (the real Anticheat):
You need to get cfemen´s  bypass. I have on the table a button to his patreon.
Sorry, I didn´t know people could ask questions on Git-hub.
